### ISSUE TITLE
CONTRIBUTING.md links are broken

### ISSUE THREAD

**Issue by BallaMatt03** [jimmyleray/Emendare#125]
**Version**
master branch
develop branch

**Describe the bug**
CONTRIBUTING.md links are broken (Issues and Board ticket)

**To Reproduce**

1. Go to Guide for Contributors
2. Click on 'Issues' or 'Board ticket'
4. See 404 errors from gitlab.com

**Expected behavior**
Links are not broken and we arrive on dedicated pages

**Comment by jimmyleray** [comment]
Welcome and thank you very much for this issue! :-) 
It has been corrected by #126
