### ISSUE TITLE
Add an avatar to profile

### ISSUE THREAD

**Issue by gwenker** [jimmyleray/Emendare#270]
**Is your feature request related to a problem? Please describe.**
Add possibility to upload an avatar in profile page.
Display avatar to better identify when you are logged in.

**Describe the solution you'd like**
Add upload file feature in profile page.
Display avatar beside to My Profile.

**Describe alternatives you've considered**
Maybe gravatar could be an option to add avatar.

**Comment by jimmyleray** [comment]
Thanks for issue ! :-) If the problem is to better visualize when we are connected or not, maybe we can find a simpler solution than to add avatars?

**Comment by gwenker** [comment]
@jimmyleray It's not only for better visualize when we are connected but also to prepare next feature about discussion for each text or amendments

**Comment by jimmyleray** [comment]
First, we test the anonymous side of the exchanges on the site. 
So it reduces the interest of adding an avatar on his profile.
But if we come back to that, the issue will rest indeed.
